### PR TITLE
fix: Imported variables are not used in other variables

### LINKED ISSUE #2408: Imported variables cannot be used in other variables
Imported variables cannot be used in other variables.

Example repository: [https://github.com/hendrikheil/devspace-import-issues](https://github.com/hendrikheil/devspace-import-issues)

### PR DESCRIPTION
**Pull request by pratikjagrut**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind bugfix

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #2408 

**Please provide a short message that should be published in the DevSpace release notes**
Fixed an issue where DevSpace was not using imported variables in defining another variable in main devspace.yaml

### CODE REVIEW

File: pkg/devspace/config/loader/variable/resolver.go [hunk 1]
```diff
@@ -386,7 +386,13 @@ func (r *resolver) resolve(ctx context.Context, name string, definition *latest.
...
 
 	// set variable so that we don't ask again
-	r.memoryCache[name] = value
+	if v, ok := value.(string); ok {
+		if v != "" {
+			r.memoryCache[name] = value
+		}
+	} else {
+		r.memoryCache[name] = value
+	}
```
Comment (lizardruss) [inline pkg/devspace/config/loader/variable/resolver.go:395]: This might make it so the importer cannot set a variable to `""`.

File: e2e/tests/imports/testdata/conditional/devspace.yaml [hunk 2]
```diff
@@ -3,13 +3,18 @@ name: base
...
   - path: ./${IMPORT1_PATH}
+  - path: ./import.yaml
 
 vars:
   IMPORT1_PATH:
     source: env
     default: import1.yaml
+  TODAYS_MESSAGE:
+    source: command
+    command: echo ${NEW_MESSAGE}
```
Comment (lizardruss) [inline e2e/tests/imports/testdata/conditional/devspace.yaml:14]: Can we add a case for when both have a var with the same name, where the importer sets the value to `""`?

I suspect that the imported value would be used over the local value, which may be unexpected.

**Review by lizardruss — CHANGES_REQUESTED** [review]
There could be unexpected behavior with the current implementation. I'll ask for a second opinion as well.

**Review by FabianKramm — APPROVED** [review]
